server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:file:memdb1?mode=memory&cache=shared
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      idle-timeout: 0
      max-lifetime: 0

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

app:
  jwt:
    secret: 8a21e9f73f344f6fab18207b15f286ce8a21e9f73f344f6fab18207b15f286ce