apiVersion: v1
kind: ConfigMap
metadata:
  name: carsales-config
data:
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:sqlite:file:memdb1?mode=memory&cache=shared"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "create-drop"
